// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroUH.Infrastructure.Data;

#nullable disable

namespace TeatroUH.Infrastructure.Migrations
{
    [DbContext(typeof(TeatroUHDbContext))]
    [Migration("20260128015941_AddNewsItem")]
    partial class AddNewsItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroUH.Domain.Entities.NewsItem", b =>
                {
                    b.Property<int>("NewsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsItemId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsItemId");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            NewsItemId = 1,
                            Content = "El Teatro Nacional anuncia la apertura de nuevas fechas para la temporada 2026. Se incluyen funciones adicionales, horarios especiales y actividades para público familiar.",
                            ImageUrl = "https://via.placeholder.com/1200x600",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Se habilitan nuevas fechas para obras clásicas y producciones nacionales.",
                            Title = "Temporada 2026: nuevas funciones confirmadas"
                        },
                        new
                        {
                            NewsItemId = 2,
                            Content = "Se actualizó el flujo de reserva para hacerlo más claro. Ahora el usuario puede revisar su carrito y confirmar con mayor facilidad.",
                            ImageUrl = "https://via.placeholder.com/1200x600",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Optimización del proceso de reserva y confirmación de entradas.",
                            Title = "Mejoras en la experiencia de compra"
                        },
                        new
                        {
                            NewsItemId = 3,
                            Content = "Durante la semana de mantenimiento se estarán realizando trabajos internos. En caso de cambios en funciones, se notificará mediante esta sección.",
                            ImageUrl = "https://via.placeholder.com/1200x600",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 1, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Algunas funciones podrían reprogramarse durante la semana de mantenimiento.",
                            Title = "Horario especial por mantenimiento"
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Play", b =>
                {
                    b.Property<int>("PlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PlayId");

                    b.ToTable("Plays");

                    b.HasData(
                        new
                        {
                            PlayId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Obra clásica",
                            DurationMinutes = 120,
                            ImageUrl = "https://via.placeholder.com/300x200",
                            IsActive = true,
                            Rating = "A",
                            Title = "Romeo y Julieta"
                        },
                        new
                        {
                            PlayId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Título extremadamente corto para probar visual.",
                            DurationMinutes = 60,
                            ImageUrl = "https://via.placeholder.com/300x200",
                            IsActive = true,
                            Rating = "B",
                            Title = "La"
                        },
                        new
                        {
                            PlayId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Texto intencionalmente largo para estresar el diseño cuando el contenido supera el ancho normal del contenedor.",
                            DurationMinutes = 145,
                            ImageUrl = "https://via.placeholder.com/300x200",
                            IsActive = true,
                            Rating = "C",
                            Title = "La increíble y absolutamente innecesariamente larga historia del teatro experimental contemporáneo"
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Showtime", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlayId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsSold")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("PlayId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            ShowtimeId = 1,
                            BasePrice = 5500m,
                            Capacity = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlayId = 1,
                            SeatsSold = 0,
                            StartDateTime = new DateTime(2026, 2, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            TheaterId = 1
                        },
                        new
                        {
                            ShowtimeId = 2,
                            BasePrice = 5500m,
                            Capacity = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlayId = 1,
                            SeatsSold = 0,
                            StartDateTime = new DateTime(2026, 2, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            TheaterId = 1
                        },
                        new
                        {
                            ShowtimeId = 3,
                            BasePrice = 3000m,
                            Capacity = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlayId = 2,
                            SeatsSold = 0,
                            StartDateTime = new DateTime(2026, 2, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            TheaterId = 2
                        },
                        new
                        {
                            ShowtimeId = 4,
                            BasePrice = 12000m,
                            Capacity = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlayId = 3,
                            SeatsSold = 0,
                            StartDateTime = new DateTime(2026, 2, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            TheaterId = 3
                        },
                        new
                        {
                            ShowtimeId = 5,
                            BasePrice = 7500m,
                            Capacity = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlayId = 3,
                            SeatsSold = 0,
                            StartDateTime = new DateTime(2026, 2, 11, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            TheaterId = 1
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Theater", b =>
                {
                    b.Property<int>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheaterId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TheaterId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            TheaterId = 1,
                            Capacity = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "San José",
                            Name = "Teatro Central"
                        },
                        new
                        {
                            TheaterId = 2,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "SJ",
                            Name = "TN"
                        },
                        new
                        {
                            TheaterId = 3,
                            Capacity = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Centro Histórico de San José, Costa Rica",
                            Name = "Teatro Nacional de Artes Escénicas y Representaciones Dramáticas de Gran Escala"
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.TicketType", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("PriceFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("TicketTypeId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            TicketTypeId = 1,
                            IsActive = true,
                            Name = "General",
                            PriceFactor = 1.0000m
                        },
                        new
                        {
                            TicketTypeId = 2,
                            IsActive = true,
                            Name = "VIP",
                            PriceFactor = 1.5000m
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@teatrouh.com",
                            Nombre = "Administrador",
                            Password = "Admin123*",
                            Role = 2
                        });
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TeatroUH.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Showtime", b =>
                {
                    b.HasOne("TeatroUH.Domain.Entities.Play", "Play")
                        .WithMany("Showtimes")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroUH.Domain.Entities.Theater", "Theater")
                        .WithMany("Showtimes")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Play");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Play", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("TeatroUH.Domain.Entities.Theater", b =>
                {
                    b.Navigation("Showtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
